/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { MyERC20 } from "./MyERC20";
export * as factories from "./factories";
export { IERC20__factory } from "./factories/IERC20__factory";
export { MyERC20__factory } from "./factories/MyERC20__factory";
